import argparse
import os

from firmware_addresses import (
	DEFAULT_REVISION,
	DEFAULT_VERSION,
	FirmwareAddressError,
	get_firmware_addresses,
)


DEFAULT_OUTPUT = "src/loader/start.inc"


def build_start_code(address):
	return f'''/* Auto-generated by generate_start.py. Do not edit! */

void playbrew_loader_start(void) __attribute__((naked, section(".firmware_hook")));

void playbrew_loader_start(void) {{
	__asm__ __volatile__ (
		"nop\\n"
		"nop\\n"
		"push {{r0, r1, r2, r3, r12, lr}}\\n"
		"bl playbrew_loader_load\\n"
		"pop {{r0, r1, r2, r3, r12, lr}}\\n"
		"ldr.w pc, ={hex(address)}\\n"
		"nop\\n"
		"nop\\n"
	);
}}
'''


def parse_args():
	parser = argparse.ArgumentParser(
		description="Generate the loader start trampoline for a known firmware target.",
	)
	parser.add_argument(
		"output",
		nargs="?",
		default=DEFAULT_OUTPUT,
		help=f"Path to write the generated include. Defaults to {DEFAULT_OUTPUT}.",
	)
	parser.add_argument("--version", default=DEFAULT_VERSION, help="Playdate OS version")
	parser.add_argument(
		"--revision",
		"--target",
		dest="revision",
		default=DEFAULT_REVISION,
		help="Playdate hardware revision, such as A or B",
	)
	return parser.parse_args()


def main():
	args = parse_args()
	addresses = get_firmware_addresses(version=args.version, revision=args.revision)
	try:
		continuation_address = addresses.require_continuation_address()
	except FirmwareAddressError as exc:
		raise SystemExit(f"error: {exc}") from None

	output_dir = os.path.dirname(args.output)
	if output_dir:
		os.makedirs(output_dir, exist_ok=True)

	with open(args.output, "w") as f:
		f.write(build_start_code(continuation_address))


if __name__ == "__main__":
	main()
