import os
import sys


# todo: make this address dynamically generated
ADDRESS = 0x240c5db3
DEFAULT_OUTPUT = "src/loader/start.inc"

START_CODE = f'''/* Auto-generated by generate_start.py. Do not edit! */

void playbrew_loader_start(void) __attribute__((naked, section(".firmware_hook")));

void playbrew_loader_start(void) {{
	__asm__ __volatile__ (
		"nop\\n"
		"nop\\n"
		"push {{r0, r1, r2, r3, r12, lr}}\\n"
		"bl playbrew_loader_load\\n"
		"pop {{r0, r1, r2, r3, r12, lr}}\\n"
		"ldr.w pc, ={hex(ADDRESS)}\\n"
		"nop\\n"
		"nop\\n"
	);
}}
'''

output_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUTPUT
output_dir = os.path.dirname(output_path)
if output_dir:
	os.makedirs(output_dir, exist_ok=True)

with open(output_path, "w") as f:
	f.write(START_CODE)
