# todo: make this address dynamically generated
# this is the return address when PBL is done running
ADDRESS = 0x240c5db3

START_CODE = f'''/* Auto-generated by generate_start.py. Do not edit! */

void playbrew_loader_start(void) __attribute__((naked, section(".firmware_hook")));

void playbrew_loader_start(void) {{
	__asm__ __volatile__ (
		"nop\\n"
		"nop\\n"
		"bl playbrew_elevator\\n"
		"mov.w r3, #{hex(ADDRESS & 0xffff)}\\n"
		"movt r3, #{hex(ADDRESS >> 16)}\\n"
		"bx r3\\n"
		"nop\\n"
		"nop\\n"
	);
}}
'''

with open("src/loader/start.inc", "w") as f:
	f.write(START_CODE)
